#!/usr/bin/env bash

# Name:     dev-tmux
# Author:   David Vogel <david@davidvogel.xyz>
# Date:     2025 Sep 7, Sun
# License:  GPL v3.0
# Desc:     dev-tmux allows a user to start `tmux` with a "session loadout"

# `PREF_SESH` will be the open session when `dev-tmux` returns
PREF_SESH="homedir"

# `SESH` is an array of sessions to open
# The format is `"<NAME>:<PATH>"`
# Note that the list's order is preserved
SESH=(
    "${PREF_SESH}:${HOME}"
    "scratch:${HOME}"
)

# NOTE: the `sleep 1` is crucial for preserving the order of the sessions
dt_loop() {
    for s in "${SESH[@]}"; do
        s_name="${s%%:*}"
        s_path="${s##*:}"

        echo "[INFO]: Creating session for \"$s_name\"."
        tmux new-session -ds "$s_name" -c $s_path
        sleep 1
    done
}

main() {
    dt_loop

    echo "[INFO]: Attaching to \"${PREF_SESH}\"."
    tmux a -t ${PREF_SESH}
}

main
