#!/usr/bin/env bash

# Name:     git_package_manager
# Author:   David Vogel <david@davidvogel.xyz>
# Date:     2025 Sep 14, Sun
# License:  GPL v3.0
# Desc:     `git_package_manager` makes managing Git repos easy

SRC_DIR="${HOME}/.local/src"
MSG_REPO_UP_TO_DATE="Already up to date."

git_mgmt() {
    if ! [[ -d .git ]]; then
        dirs_not_repos+=("$dir")
        return 0
    fi

    echo "[INFO]: Attempting to update \"$dir\"."

    git fetch > /dev/null 2>&1
    local EXIT_CODE="$?"

    if [[ "$EXIT_CODE" == 128 ]]; then
        repos_bad_fetch+=("$dir")
        return 0
    fi

    # cannot use `local OUTPUT`, or `$EXIT_CODE` always equals `0`
    OUTPUT=$(git pull 2>/dev/null)
    EXIT_CODE="$?"

    if [[ "$EXIT_CODE" == 1 ]]; then
        repos_no_branch+=("$dir")
        return 0
    elif [[ "$EXIT_CODE" == 128 ]]; then
        repos_bad_pull+=("$dir")
        return 0
    fi

    if [[ "$OUTPUT" == "$MSG_REPO_UP_TO_DATE" ]]; then
        repos_no_change+=("$dir")
        return 0
    fi

    if ! [[ "$OUTPUT" == "$MSG_REPO_UP_TO_DATE" ]]; then
        repos_updated+=("$dir")
    fi
}

gpm-loop() {
    for dir in *; do
        if ! [[ -d $dir ]]; then
            not_dirs+=("$dir")
            continue
        fi

        cd $dir

        # operate within dir
        git_mgmt

        cd ..
    done
}

gpm-results() {
    if ! [[ "${#not_dirs[@]}" == 0 ]]; then
        echo
        echo "[INFO]: The following objects are not directories:"

        printf -- "- %s\n" "${not_dirs[@]}"
    fi

    if ! [[ "${#dirs_not_repos[@]}" == 0 ]]; then
        echo
        echo "[INFO]: The following directories are not Git repos:"

        printf -- "- %s\n" "${dirs_not_repos[@]}"
    fi

    if ! [[ "${#repos_no_change[@]}" == 0 ]]; then
        echo
        echo "[INFO]: The following Git repos were already up-to-date:"

        printf -- "- %s\n" "${repos_no_change[@]}"
    fi

    if ! [[ "${#repos_updated[@]}" == 0 ]]; then
        echo
        echo "[INFO]: The following Git repos were updated successfully:"

        printf -- "- %s\n" "${repos_updated[@]}"
    fi

    if ! [[ "${#repos_no_branch[@]}" == 0 ]]; then
        echo
        echo "[INFO]: The following Git repos were updated without changing HEAD:"

        printf -- "- %s\n" "${repos_no_branch[@]}"
    fi

    if ! [[ "${#repos_bad_fetch[@]}" == 0 ]]; then
        echo
        echo "[WARN]: The following Git repos did not fetch cleanly:"

        printf -- "- %s\n" "${repos_bad_fetch[@]}"
    fi

    if ! [[ "${#repos_bad_pull[@]}" == 0 ]]; then
        echo
        echo "[WARN]: The following Git repos did not pull cleanly:"

        printf -- "- %s\n" "${repos_bad_pull[@]}"
    fi
}

main() {
    not_dirs=()
    dirs_not_repos=()
    repos_bad_fetch=()
    repos_no_branch=()
    repos_bad_pull=()
    repos_no_change=()
    repos_updated=()

    cd $SRC_DIR

    gpm-loop

    gpm-results
}

main
