#!/usr/bin/env bash

# Name:     git_compare_dates
# Author:   David Vogel <david@davidvogel.xyz>
# Date:     2025 Sep 8, Mon
# License:  GPL v3.0
# Desc:     `git_compare_dates` quickly checks author vs committer info

count=0

check_git_repo() {
    git status > /dev/null 2>&1

    if [[ $? == 128 ]]; then
        echo "[ERROR]: The current directory is not a Git repo."
        exit 1
    fi
}

gcd_loop() {
    echo "[INFO]: Performing the loop..."

    while read -r line; do
        case "$line" in
            commit*)
                local commithash="${line##* }";
                commithash="${commithash:0:7}";
                ;;
            Author:*)
                local authorname="${line##*:     }";;
            AuthorDate*)
                local authordate="${line##*: }";;
            Commit:*)
                local commitauthorname="${line##*:     }";

                if ! [[ "$authorname" == "$commitauthorname" ]]; then
                    echo "[WARN]: Author names do not agree for commit \"$commithash\"."
                    echo "[WARN]: ${commithash}: \"$authorname\" vs \"$commitauthorname\""
                    count+=1
                    hash_oldest_disagreement="$commithash"
                fi;;
            CommitDate*)
                local committerdate="${line##*: }";

                if ! [[ "$authordate" == "$committerdate" ]]; then
                    echo "[WARN]: Dates do not agree for commit \"$commithash\"."
                    echo "[WARN]: ${commithash}: \"$authordate\" vs \"$committerdate\""
                    count+=1
                    hash_oldest_disagreement="$commithash"
                fi;;
            *)
                continue;;
        esac
    done < <(git log --pretty=fuller | grep -A 4 "^commit")
}

gcd_results() {
    echo "[INFO]: Comparison complete."

    if (( count == 0 )); then
        echo -e "\n[INFO]: No disagreements detected!"
    fi

    if ! (( count == 0 )); then
        local idx=1

        while read -r line; do
            # Skip the oldest disagreement
            if (( idx == 1 )); then
                idx=$(( idx + 1 ))
                continue
            fi

            # Grab the hash of the previous commit
            if (( idx == 2 )); then
                local hash_rebase="${line%% *}"
            fi
        done < <(git log --oneline | grep -i -A 1 "^${hash_oldest_disagreement}")

        # If `hash_rebase` is unset, it should be the "root" commit
        if ! [[ "$hash_rebase" ]]; then
            local hash_rebase="the root commit."
        else
            hash_rebase="commit $hash_rebase"
        fi

        echo -e "\n[INFO]: To address all discrepancies, rebase from ${hash_rebase}"
    fi
}

main() {
    if ! [[ "$(command -v git)" ]]; then
        error "[ERROR]: Git does not appear to be installed. Exiting now."
    fi

    check_git_repo
    gcd_loop
    gcd_results
}

main
