#!/usr/bin/env bash

# Name:     openssl-password-hash
# Author:   David Vogel <david@davidvogel.xyz>
# Date:     2025 Jul 13, Sun
# License:  GPL v3.0
# Desc:     `openssl-password-hash` hashes passwords for use with `/etc/shadow`.

ask_static_salt() {
    read -r -p "Please provide a static salt. " static_salt
}

main() {
    ask_static_salt

    openssl passwd -salt $static_salt -6
}

main
